[build]
  # No 'base' property here. Commands will run from the repository root.
  publish = "frontend/dist" # This is where Netlify will find the final build output.
  installCommand = "cd frontend && npm install" # Change to frontend, then install.
  buildCommand = "cd frontend && npm run build" # Change to frontend, then run the build script.

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache"
