[build]
  base = "frontend/"
  publish = "dist"
  installCommand = "npm install"
  buildCommand = "./node_modules/.bin/vite build" # Explicitly call vite build from its local path

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache"
